# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false
r_build_args: "--no-manual"
r_check_args: "--no-manual"
env:
  global:
    - RGL_USE_NULL=TRUE
    - MAKEFLAGS="-j 2"
    - CRAN: https://cran.rstudio.com
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
